
title: My Resume
url: 'https://alspeed09.github.io'
baseurl: '/Alfredo_Ascanio' #change it according to your repository name



# Profile information
yourname: Alfredo Ascanio ## put your name
title: 'ECOLOGIST &amp; DATA SCIENTIST'  ## your title
location: Caracas, Venezuela


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
github: https://github.com/alspeed09 ## my github account
twitter: https://twitter.com/alspeed09  ## your twitter account url
linkedin: https://www.linkedin.com/in/ascanioalfredo/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
